--Primeiro iremos criar duas bases de dados
IF EXISTS(SELECT NAME FROM sys.databases WHERE NAME = 'TESTE_LOGIN')
	DROP DATABASE TESTE_LOGIN

CREATE DATABASE TESTE_LOGIN

--SCRIPT PARA CRIAR LOGIN E USUÁRIO
--LOGIN
CREATE LOGIN [Matheus_1] WITH PASSWORD=N'Sql@123', 
DEFAULT_DATABASE=TESTE_LOGIN, 
CHECK_EXPIRATION=OFF, CHECK_POLICY=ON

GO
--USUÁRIO
USE TESTE_LOGIN
GO
CREATE USER [Matheus_1] FOR LOGIN [Matheus_1]
GO

--CRIANDO TABELA PARA TESTE 
CREATE TABLE DADOSLOGIN(
	Id INT IDENTITY,
	Data_dados DATETIME DEFAULT(GETDATE()),
	Dados_teste VARCHAR(100))
GO

--INSERINDO 20 LINHAS
INSERT INTO DADOSLOGIN(Dados_teste)
SELECT 'TESTANDO LOGIN'
GO 20

--LIBERANDO ACESSO A UMA TABELA
--LEMBRANDO QUE TEMOS QUE COLOCAR A BASE DE DADOS EM USO PARA QUE A TABELA SEJA ENCONTRADA
USE TESTE_LOGIN

GRANT SELECT ON DADOSLOGIN TO Matheus_1

--NEGANDO ACESSO A TABELA
--LEMBRANDO QUE TEMOS QUE COLOCAR A BASE DE DADOS EM USO PARA QUE A TABELA SEJA ENCONTRADA
USE TESTE_LOGIN

DENY SELECT ON DADOSLOGIN TO Matheus_1

--PERMITINDO ACESSO A PROCEDURE
--CRIANDO PROCEDURE
USE TESTE_LOGIN

CREATE PROCEDURE stpTestePermissao
AS 
BEGIN
	SELECT * FROM DADOSLOGIN
END

EXEC stpTestPermissao

--DANDO PERMISSÃO A PROCEDURE stpTestePermissao
GRANT EXECUTE ON stpTestePermissao TO Matheus_1

--UTILIZANDO O COMANDO REVOKE PARA TIRAR A ÚLTIMA PERMISSÃO DADA A PROCEDURE
REVOKE EXECUTE ON stpTestePermissao TO Matheus_1