--Primeiro iremos criar duas bases de dados
IF EXISTS(SELECT NAME FROM sys.databases WHERE NAME = 'TESTE_LOGIN')
	DROP DATABASE TESTE_LOGIN

CREATE DATABASE TESTE_LOGIN

IF EXISTS(SELECT NAME FROM sys.databases WHERE NAME = 'TESTE_LOGIN_2')
	DROP DATABASE TESTE_LOGIN_2

CREATE DATABASE TESTE_LOGIN_2

--SCRIPT PARA CRIAR LOGIN E USUÁRIO
--LOGIN
CREATE LOGIN [Matheus_1] WITH PASSWORD=N'Sql@123', 
DEFAULT_DATABASE=TESTE_LOGIN, 
CHECK_EXPIRATION=OFF, CHECK_POLICY=ON

GO
--USUÁRIO
USE TESTE_LOGIN
GO
CREATE USER [Matheus_1] FOR LOGIN [Matheus_1]
GO

--CRIANDO TABELA PARA TESTE 
CREATE TABLE DADOSLOGIN(
	Id INT IDENTITY,
	Data_dados DATETIME DEFAULT(GETDATE()),
	Dados_teste VARCHAR(100))
GO

--INSERINDO 20 LINHAS
INSERT INTO DADOSLOGIN(Dados_teste)
SELECT 'TESTANDO LOGIN'
GO 20

